# Generated by Django 3.1.7 on 2021-05-04 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kurzy', '0002_auto_20210420_2036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prihlaska',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('jmeno', models.CharField(max_length=100)),
                ('prijmeni', models.CharField(max_length=100)),
                ('motivace', models.TextField()),
                ('kurz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kurzy.kurz')),
            ],
        ),
    ]
