# Generated by Django 3.1.7 on 2021-04-20 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_organizace'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizace',
            name='kontakt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.kontakt'),
        ),
    ]
