# Generated by Django 3.1.7 on 2021-05-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_organizace_kontakt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organizace',
            old_name='identifikacni_cislo',
            new_name='ico',
        ),
    ]
